# Documentation: https://roots.io/trellis/docs/local-development-setup/
# wordpress_sites options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  testing.com:
    site_hosts:
      - canonical: testing.com.dev
        redirects:
          - www.testing.com.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: admin@testing.com.dev
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
